name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Cloudflare Worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        usewhos: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            curl https://sh.rustup.rs -sSf | bash -s -- -y
            source $HOME/.cargo/env
