name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy Cloudflare Worker"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        rust: ["stable"]
    continue-on-error: ${{ matrix.rust != 'stable' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Check rust
        run: which cargo
      - name: Check rust
        run: cargo --version
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: echo "which cargo"
